apiVersion: v1
kind: Service
metadata:
  labels:
    app: lounge
    name: lounge
  name: lounge
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: lounge
status:
  loadBalancer: {}
