apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:9.3.0
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_ROOTPWD

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: meetups-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meetups-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: Service
metadata:
  name: meetup-mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
