apiVersion: v1
data:
  MYSQL_DATABASE: bGFyYXZlbA==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOTPWD: cm9vdHB3ZA==
  MYSQL_USER: YWxleA==
kind: Secret
metadata:
  creationTimestamp: null
  name: env-secret
